import { UserProvider } from '../context/userContext';
import "./globals.css";

export const metadata = {
  title: "Edulink",
  description: "Generated by UC-Games",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-roboto antialiased">
        <UserProvider>
          {children}
        </UserProvider>
      </body>
    </html>
  );
}